### ISSUE TITLE
API operations not yet documented

### ISSUE THREAD

**Issue by jlewis666** [mastodon/documentation#1475] opened 2024-07-08 08:57 UTC
The following API operations appear to be currently undocumented:

GET /api/v1/admin/tags/{id}
GET /api/v1/admin/trends/links/publishers
GET /api/v1/emails/check_confirmation
GET /api/v1/instance/languages
GET /api/v1/instance/privacy_policy
GET /api/v1/peers/search
GET /api/v1/polls/{pollId}
GET /api/v1/tests
GET /api/v1/timelines/link
GET /api/v1/timelines/tag/test
POST /api/v1/admin/trends/links/{id}/approve
POST /api/v1/admin/trends/links/{id}/reject
POST /api/v1/admin/trends/links/publishers/{id}/approve
POST /api/v1/admin/trends/links/publishers/{id}/reject
POST /api/v1/admin/trends/statuses/{id}/approve
POST /api/v1/admin/trends/statuses/{id}/reject
POST /api/v1/admin/trends/tags/{tagid}/approve
POST /api/v1/admin/trends/tags/{tagid}/reject
POST /api/v1/conversations/{id}/unread
POST /api/v1/polls/{pollId}/votes
PUT /api/v1/admin/tags/{id}
PUT /api/v1/notifications/policy

**Comment by trwnh** [comment] 2024-07-11 00:59
#1211

**Comment by andypiper** [comment] 2024-08-03 17:01
Closing as duplicate of #1211

**Closed by andypiper** 2024-08-03 17:01 UTC
Labels: duplicate
