### ISSUE TITLE
Update documentation to include new full-text search keywords

### ISSUE THREAD

**Issue by quinncomendant** [mastodon/documentation#1325] opened 2023-09-01 23:01 UTC
### Steps to reproduce the problem

The [Mastodon documentation for Search](https://docs.joinmastodon.org/user/network/#search) mentions “Admins may optionally install full-text search” but it doesn't list the new keyword operators that were added (`has:`, `is:`, `from:`, `before:`, etc).

### Expected behaviour

The documentation should contain all search parameters

### Actual behaviour

The documentation lacks this info

**Comment by vmstan** [comment] 2023-11-23 21:07
Duplicate of #1286

**Closed by vmstan** 2023-11-23 21:07 UTC
Labels: bug
